project:
  type: book
  output-dir: docs

book:
  title: "Introducción al análisis estadístico de datos con R"
  subtitle: "Modelización de la calidad del aire en la ciudad de Madrid con la metodología CRISP-DM"
  author:
    - Gema Fernández-Avilés
    - Michal Kinel
  date: today
  description: |
    Este libro ofrece una guía práctica para el análisis de datos con el software estadístico R mediante 
    la aplicación de la metodología *Cross-Industry Standard Process for Data Mining* (CRISP-DM).
  cover-image: cover.png
  chapters:
    - index.qmd
    - 001-Introduccion.qmd
    - 002-toolkit-ciencia-datos.qmd
    - 003-crispdm-air-madrid.qmd
  appendices:
    - 00a-pre-curso.qmd
  search: false
bibliography: references.bib
crossref:
  fig-title: Figura     # (default is "Figure")
  tbl-title: Tabla     # (default is "Table")

format:
  html:
    theme: custom.scss
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/lato" type="text/css"/>
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/fira-code" type="text/css"/>
    mainfont: LatoRegular
    monofont: FiraCodeRegular
    toc: true
    toc-depth	: 2
    toc-location: right
    toc-title: "Contenidos"
    number-sections: true
    linestretch: 1.5
    fig-cap-location: bottom
    tbl-cap-location: top
    code-block-border-left: true
    execute:
      warning: false
      message: false
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true


editor: source

language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    cor: 'Corolario '
    prp: 'Proposición '
    cnj: 'Conjetura '
    def: 'Definición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    hyp: 'Hipótesis '
    proof: 'Prueba. '
    remark: 'Observación. '
    solution: 'Solución. '
  ui:
    chapter_name: 'Capítulo '
    appendix_name: 'Anexo '

