# Bibliografía {#bibliografía}

1. Chapman, P., Clinton, J., Kerber, R., Khabaza, T., Reinartz, T., Shearer, C., & Wirth, R. (2000). CRISP-DM 1.0: Step-by-step data mining guide. SPSS.
2. Kuhn, M., & Johnson, K. (2013). Applied Predictive Modeling. Springer.
3. James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). An Introduction to Statistical Learning: with Applications in R. Springer.
4. Hastie, T., Tibshirani, R., & Friedman, J. (2009). The Elements of Statistical Learning: Data Mining, Inference, and Prediction. Springer.
5. Hastie, T., Tibshirani, R., & Friedman, J. (2017). The Elements of Statistical Learning: Data Mining, Inference, and Prediction (2nd ed.). Springer.
6. Kuhn, M. (2008). Building Predictive Models in R Using the caret Package. Journal of Statistical Software, 28(5), 1-26.
7. Peña, D., Tiao, G. C., & Tsay, R. S. (2001). A Course in Time Series Analysis. Wiley.
8. Hyndman, R. J., & Athanasopoulos, G. (2018). Forecasting: Principles and Practice (2nd ed.). OTexts.
9. Wickham, H. (2019). Mastering Shiny. O'Reilly Media.
10. Chang, W., Cheng, J., Allaire, J., Xie, Y., & McPherson, J. (2021). shiny: Web Application Framework for R. R package version 1.6.0.
11. Gentry, J. (2017). rtweet: Collecting Twitter Data. Journal of Open Source Software, 2(16), 1-3.
12. Xie, Y., Allaire, J., & Grolemund, G. (2018). R Markdown: The Definitive Guide. CRC Press.
13. R Core Team. (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing. https://www.R-project.org/
14. RStudio Team. (2021). RStudio: Integrated Development for R. RStudio, PBC. http://www.rstudio.com/
15. Pebesma, E. (2018). Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal, 10(1), 439-446.
16. Hijmans, R. J. (2020). raster: Geographic Data Analysis and Modeling. R package version 3.4-13.
17. Bivand, R., Keitt, T., & Rowlingson, B. (2021). rgdal: Bindings for the Geospatial Data Abstraction Library. R package version 1.5-27.
18. Wickham, H., & Grolemund, G. (2016). R for Data Science: Import, Tidy, Transform, Visualize, and Model Data. O'Reilly Media.
19. Grolemund, G., & Wickham, H. (2011). Dates and Times Made Easy with lubridate. Journal of Statistical Software, 40(3), 1-25.
20. Pebesma, E. J., & Bivand, R. S. (2005). Classes and Methods for Spatial Data in R. R News, 5(2), 9-13.
